### ISSUE TITLE
Combinators to assert performance metrics

### ISSUE THREAD

**Issue by alexbiehl-gc** [Bodigrim/tasty-bench#1]
Super cool library! 

I could imagine there being combinators to assert performance metrics for individual test cases. Like "fail this test if it the runtime differs by x% off some baseline". 

- allow annotation of tests/benches with expected runtime + allowed deviation
- maybe even save metrics to a file and have a command line flag to accept changes 

Imagine CI checked performance regressions, very similar to what GHC does in it's CI infrastructure.

**Comment by Bodigrim** [comment]
@alexbiehl-gc could you possibly give a try to a01a3ff667b9fe55a456e4434403ec4b3d147069? I've added a basic support of baselines. It works as follows:

1. Dump benchmark results in CSV format:
```
$ cabal bench --benchmark-options '--csv fibo.csv'
All
  fibonacci numbers
    fifth:     OK (1.32s)
      155 ns ±  13 ns
    tenth:     OK (1.89s)
      1.8 μs ± 104 ns
    twentieth: OK (1.94s)
      235 μs ±  20 μs
    from file: OK (2.00s)
      1.9 μs ± 133 ns
```
2. Change implementation as desired.
3. Rerun benchmarks, providing previous report as a baseline:
```
$ cabal bench --benchmark-options '--baseline fibo.csv'
All
  fibonacci numbers
    fifth:     OK (1.46s)
      172 ns ±  15 ns
      11.3% slower than baseline
    tenth:     OK (2.08s)
      2.0 μs ± 174 ns
      11.8% slower than baseline
    twentieth: OK (4.23s)
      258 μs ±  11 μs
      9.6% slower than baseline
    from file: OK (2.18s)
      2.1 μs ± 119 ns
      9.8% slower than baseline
```

How does it look?

**Comment by alexbiehl-gc** [comment]
Sweet! I think this is a great first step! I am unsure how an assertion over these would look like. As for the assertion one possible idea could be to redefine `Benchmarkable` as 

```
data Benchmarkable = Benchmarkable { 
  benchmark            :: Int64 -> IO (),
  baselineDeviation :: Maybe Double
}
```

and have another combinator to annotate Benchmarkables. Now, if a baseline deviation and `--baseline` is present, the results are being compared and the test succeeds or fails accordingly.

**Comment by Bodigrim** [comment]
b0448b43297da71885e02356b8b02e868ba77d2d adds `--fail-if-slower PERCENT` command-line option and a corresponding `tasty` `Option` for fine-grained control:

```
$ cabal bench --benchmark-options '--baseline fibo.csv --fail-if-slower 10'
All
  fibonacci numbers
    fifth:      FAIL (1.32s)
      156 ns ±  13 ns, 24% slower than baseline
    ten.th:     OK (1.92s)
      1.8 μs ± 128 ns
    twen,tieth: OK (3.84s)
      236 μs ± 9.6 μs
    from file:  OK (2.02s)
      1.9 μs ± 177 ns

1 out of 4 tests failed (9.15s)
```
Passing `--fail-if-slower 30` still reports about 24% slowdown, but does not fail the benchmark.

If it looks good, I'll proceed with documentation.

**Comment by alexbiehl** [comment]
This is good stuff. Wanted to have this for some time at work but never got to it. Thank you for your efforts!

One last nit: Personally I’d prefer a dedicated combinator instead of raw localOption.

**Comment by alexbiehl-gc** [comment]
One thing: It might be good to have another, stricter version of the combinator that fails if too slow _or_ too fast. It would help always be on top and aware of changes that cause baseline adjustment.

**Comment by Bodigrim** [comment]
> One last nit: Personally I’d prefer a dedicated combinator instead of plain localOption.

Probably not at this stage: I'd like to see this feature getting significant traction first. 

>  It might be good to have another, stricter version of the combinator that fails if too slow or too fast. 

Good idea. Added `--fail-if-faster`.

I'd appreciate if you give this functionality a try, before I release it officially.

**Comment by Bodigrim** [comment]
https://hackage.haskell.org/package/tasty-bench-0.2.1 has been released, including this feature.
