### ISSUE TITLE
Run an IO action in the bench without timing it

### ISSUE THREAD

**Issue by kozross** [Bodigrim/tasty-bench#12]
I want to benchmark a search algorithm implementation. As a result, I'd like to generate random needles for each iteration of the bench. However, I don't want to also measure the PRNG. Is there a way to do this currently?

**Comment by Bodigrim** [comment]
It's a bit unclear to me, what design you have in mind. How would your benchmark look, if you agree to measure the PRNG overhead?

**Comment by kozross** [comment]
It would be something like:

`bench "Foo" . nfAppIO (\h -> doTheSearch <$> genRandomNeedle <*> pure h) $ haystack`

However, this will end up benchmarking both `genRandomNeedle` and the search for it, whereas I only want to benchmark the search. Furthermore, I only need IO for the random generation, not the search. The idea is that as the search is run many times during the benchmarking process, by randomizing the needle I get a good idea of 'average' performance.

**Comment by Bodigrim** [comment]
Unfortunately, I don't think there is a reasonable workaround for this particular scenario. Both individual generation of a needle and the search itself are well beyond the granulatiry of a system timer, so we cannot start-stop it. 

FWIW I think that `genRandomNeedle` implemented via http://hackage.haskell.org/package/random-1.2.0/docs/System-Random-Stateful.html#g:11 should be blazingly fast and thus would not affect overall measures in a significant way. 

In general I'm inclined to advise against such design: to achieve reliable results with a predictable deviation, it's crucial to benchmark exactly the same data over and over again. Maybe generate several thousands of needles at top level and iterate over them all in a single benchmark?..

**Comment by kozross** [comment]
Yeah, I think you're right on all counts. However, if I generate all the needles at the top level, then do them all in one bench, I'll get a result for a thousand needles, not the average for one needle. Unless I'm missing something?

**Comment by Bodigrim** [comment]
Well, you can divide by thousand to approximate the average. I agree that it's not that convenient, but absolute numbers are of limited value anyways.

**Comment by kozross** [comment]
Fair enough. Thanks for the advice!

**Comment by soupi** [comment]
A different data point - what if I want to test an external system that needs restarts, preparation or warmup/cache clearing before benchmarking? This is not something one can do outside of the testing loop. This is also something that for example [hyperfine](https://github.com/sharkdp/hyperfine) does provide.

**Comment by Bodigrim** [comment]
Unless I'm missing something, this is what [`env`](https://hackage.haskell.org/package/tasty-bench-0.2.5/docs/Test-Tasty-Bench.html#v:env) is for.

**Comment by soupi** [comment]
Does `env` run for each benchmark or for each timing run?

**Comment by Bodigrim** [comment]
`env` runs once, before measurements of a particular routine take place.
