### ISSUE TITLE
Font color might be indistinguishable from terminal foreground color

### ISSUE THREAD

**Issue by 0xd34df00d** [Bodigrim/tasty-bench#13]
I'll just paste two screenshots. My default terminal theme:
![](https://a.pomf.cat/mbjpze.png)
vs a dark one:
![](https://a.pomf.cat/vubrlg.png)

I don't think this is a problem with the color scheme, as I don't remember other cli/tui applications having this issue. On the bright side, this is a weirdest bug I've come across for a while (I was puzzled for about half an hour where did the measurements go!) which gave me a sensible chuckle after understanding the problem.

**Comment by Bodigrim** [comment]
`tasty-bench` does not color the output itself, this is up to `tasty`. Do you observe the same issue with `bytestring` tests? (I'm AFK, but I suppose QuickCheck properties report the number of tests in the same way)

**Comment by 0xd34df00d** [comment]
Yep, tests have the same problem (I just never cared about the specific number of tests to notice that). I guess I'll reopen this upstream.

**Comment by 0xd34df00d** [comment]
Alrighty, opened upstream as https://github.com/UnkindPartition/tasty/issues/298 , so closing this one.
