### ISSUE TITLE
Not enough significant figures are shown

### ISSUE THREAD

**Issue by bgamari** [Bodigrim/tasty-bench#14]
It appears that `tasty-bench` doesn't take into account the requested standard deviation when displaying results. For instance, if I pass `--stdev 1` then I would expect that three significant figures are shown. However, this is currently not the case:

```
$ cabal run bench -- --stdev 1
All
  CUChar: OK (10.28s)
    1.3 ms ± 23 μs,   0 B  allocated,   0 B  copied
```

**Comment by Bodigrim** [comment]
Thanks, fixed in 791a1ea1babea534be2635e9f6d86cb95e0b5a01.
