### ISSUE TITLE
No indication of progress with --csv

### ISSUE THREAD

**Issue by sjakobi** [Bodigrim/tasty-bench#2]
I'm currently running some benchmarks with `--stdev 1 --csv` and I'm wondering whether they will ever finish. Since there's no terminal output, I can't tell whether they are hanging at a particular benchmark.

Could terminal output be provided even when the `--csv` option is enabled, just like `criterion` and `gauge` handle it?

**Comment by sjakobi** [comment]
Oh, I think you might've already fixed this in https://github.com/Bodigrim/tasty-bench/commit/f9691c5667f8fd55af170b7eba7b46f721f96ea9. Would be great to get this released! :)

**Comment by Bodigrim** [comment]
Yep, I had exactly the same problem which motivated  f9691c5 :) I'll release 0.2 once #1 is tested. 

Also f2c98a053ea7be94167d5fd145858ae82d8f37c3 surprisingly fixes precision issues so much that de71f014ebb49d94ab1f230395f29f41c7c8712a actually sets `--stdev 1` as default.

**Comment by sjakobi** [comment]
Wow, I wouldn't have expected that `Integer` arithmetic would introduce so much jitter! Sounds like a great improvement! :)

**Comment by Bodigrim** [comment]
Ah, no surprises, just an integer overflow with `Word64` %) Fixed in c21eefc334fb62c27c31dfd83757f7e8ae1785e7
