### ISSUE TITLE
A flag to run each benchmark exactly *n* times

### ISSUE THREAD

**Issue by ocharles** [Bodigrim/tasty-bench#25]
This might be a bit of an odd one, so feel free to reject it. I'm doing some very fine performance tuning, and it would be helpful if I could run benchmarks so that each benchmark is ran a deterministic number of times. I'm actually less interested in timings here, but am very interested in total allocations, over the entire benchmark run.

**Comment by Bodigrim** [comment]
You can run exactly one iteration of each benchmark by passing `--stdev Infinity`, see https://hackage.haskell.org/package/tasty-bench-0.3.1/docs/Test-Tasty-Bench.html#t:RelStDev
Next, a constructor of `Benchmarkable` is exported, so you can do something like `runInBatchesOfN n (Benchmarkable f) = Benchmarkable (f . (* n))`. 
Finally, pass `n` as a command line parameter, see a snippet here: https://hackage.haskell.org/package/tasty-bench-0.3.1/docs/Test-Tasty-Bench.html#t:CsvPath

Does it suffice for your goal?

**Comment by ocharles** [comment]
Thanks @Bodigrim. `--stdev Infinity` is a bit subtle, but it'll do the job. Thanks!
