### ISSUE TITLE
When running benchmarks against a baseline, it is unclear whether the baseline was compared against

### ISSUE THREAD

**Issue by santiweight** [Bodigrim/tasty-bench#28]
https://github.com/Bodigrim/tasty-bench/blob/7de1e2a78c33f186279121dc68eca52c16831f5c/src/Test/Tasty/Bench.hs#L1724

The above line shows that when the change in runtime against the baseline is essentially 0, then no indication is given. The first output is a typical slowdown:

```
      41.7 ms ± 3.7 ms, 157 MB allocated,  19 MB copied,  14 MB peak memory, 97203242% slower than baseline
```

but the thing is that when running against a baseline, I want to see in words "unchanged against baseline". Not seeing that text makes it confusing as to whether the baseline was even tested against. Here is an example:

```
      41.7 ms ± 3.7 ms, 157 MB allocated,  19 MB copied,  14 MB peak memory
```

This is confusing to at least myself and my coworker. What do you think?

By the way - thanks for the awesome library!

**Comment by Bodigrim** [comment]
Closed by fce531307fd58f2b94f81ce4c8445c693fae070b
