### ISSUE TITLE
Output of the benchmark function is retained in memory

### ISSUE THREAD

**Issue by noughtmare** [Bodigrim/tasty-bench#39]
See [my discourse thread for the full story](https://discourse.haskell.org/t/a-solved-benchmarking-mystery/5738?u=jaror).

The short version is that this issue is reproduced by this program:

```haskell
import Test.Tasty.Bench
-- import Criterion.Main
import Control.DeepSeq

drop' :: Int -> [a] -> [a]
drop' n s =
      case n of
        0 ->
          case s of
            [] -> []
            x : xs -> x : drop' 0 xs
        _ ->
          case s of
            [] -> []
            x : xs -> drop' (n - 1) xs

main = do
  let input = replicate 1000000 'a'
  defaultMain
    [ bench "1" $ whnf (rnf . drop' 100000) input
    , bench "2" $ nf (drop' 100000) input
    ]
```

The result is:

```
All
  1: OK (2.67s)
    4.88 ms ± 250 μs,  41 MB allocated, 1.3 KB copied,  53 MB peak memory
  2: OK (1.72s)
    26.0 ms ± 2.6 ms,  41 MB allocated,  40 MB copied, 120 MB peak memory
```

Changing to `criterion` yields these wildly different results:

```
benchmarking 1
time                 4.943 ms   (4.867 ms .. 5.039 ms)
                     0.993 R²   (0.987 R² .. 0.998 R²)
mean                 5.130 ms   (5.039 ms .. 5.235 ms)
std dev              309.2 μs   (245.2 μs .. 386.1 μs)
variance introduced by outliers: 35% (moderately inflated)

benchmarking 2
time                 5.058 ms   (4.957 ms .. 5.163 ms)
                     0.996 R²   (0.991 R² .. 0.998 R²)
mean                 5.213 ms   (5.124 ms .. 5.349 ms)
std dev              337.9 μs   (248.5 μs .. 504.7 μs)
variance introduced by outliers: 39% (moderately inflated)
```

I've tracked it down in Core to this difference:

```haskell
-- Expression that evaluates benchmark 1
seq# (case $wgo ($wdrop' 100000# x1) of { (# #) -> () }) eta2

-- Helper function for benchmark 2
eta1 :: [Char] -> [Char]
eta1 = \ (s :: [Char]) -> $wdrop' 100000# s

-- Expression that evaluates benchmark 2
seq#
  (let {
    x2 :: [Char]
    x2 = eta1 x1 } 
   in
    case $wgo x2 of { (# #) -> x2 })
  eta2
```

This shows benchmark 2 retains `x2` in memory during the normalization (`$wgo`).

I think this can be solved by using `rnf` instead of `force`:

```diff
-nf = funcToBench force
+nf = funcToBench rnf
```

**Comment by Bodigrim** [comment]
Should `whnf` in this case be defined as `whnf = funcToBench seq`?

**Comment by noughtmare** [comment]
I don't think `whnf` needs to be changed. Only `nf`, `nfIO`, and `nfAppIO`.

**Comment by Bodigrim** [comment]
Well, it would be more symmetric to change both. 

I'm sorry, I'm terribly overloaded at the moment. If you can take a bench suite of, say, `bytestring` or `containers` and check the effect of `nf = funcToBench rnf`, I'll be very grateful.

**Comment by noughtmare** [comment]
OK, I'll make the change and try it out on your existing suites.

**Comment by noughtmare** [comment]
Here's the raw results for bytestring:

[rnf-bytestring-after.csv](https://github.com/Bodigrim/tasty-bench/files/10608446/rnf-bytestring-after.csv)
[rnf-bytestring-before.csv](https://github.com/Bodigrim/tasty-bench/files/10608448/rnf-bytestring-before.csv)

And the full output of the command line (including the baseline comparisons):

[out.log](https://github.com/Bodigrim/tasty-bench/files/10608447/out.log)

The most remarkable result is that `unpack` consistently takes about 200% more time. I will investigate that further.

**Comment by noughtmare** [comment]
I've been convinced by Andreas Klebinger that using `force` is actually more representative of the (worst case) real world behavior. And it is easy to get the other behavior by just including `rnf` in your benchmark. So, perhaps all that should be done is adding some documentation to explain this.

**Comment by Bodigrim** [comment]
Documentation patch is welcome.

**Comment by Bodigrim** [comment]
I've updated documentation in 461919e.

**Comment by Bodigrim** [comment]
However, this change would have to wait until `tasty-bench-0.4`, which in its turn awaits `tasty-1.5` to be released, so probably somewhere in September.

**Comment by Bodigrim** [comment]
Changed in 3ce8baf8260582d10b0894bc2bbd6b3105b41a5a.
