### ISSUE TITLE
Recommend mitigations for benchmark instability introduced by GHCs SpecConstr.

### ISSUE THREAD

**Issue by AndreasPK** [Bodigrim/tasty-bench#44]
As part of the ghc-9.6 release process we the GHC team has been investigating various performance
changes in libraries and discovered that GHCs SpecConstr pass can get in the way of
benchmark stability.

# The problem

The core of the issue is that by default  `SpecConstr` specializes a function
to it's argument only at limited number of call sites. This is controlled by the `-fspec-constr-count`
flag and by default the number of specializations is three.

This can be problematic for benchmarks which often look like this:

```haskell
        [ bench "FindIndices/inlined"     $ nf (S.findIndices    (== nl)) absurdlong
        , bench "FindIndices/non-inlined" $ nf (S.findIndices (nilEq nl)) absurdlong
        , bench "FindIndex/inlined"       $ nf (S.findIndex      (== nl)) absurdlong
        , bench "FindIndex/non-inlined"   $ nf (S.findIndex   (nilEq nl)) absurdlong
        ]
```

Why is this problematic? Before SpecConstr is run the above snipped will have been
transformed into something along the lines of:

```
bench1 = $wbenchLoop (S.findIndices    (== nl)) absurdlong
bench2 = $wbenchLoop (S.findIndices (nilEq nl)) absurdlong
bench3 = $wbenchLoop (S.findIndex      (== nl)) absurdlong
bench4 = $wbenchLoop (S.findIndex   (nilEq nl)) absurdlong
```

This is problematic as we now have four calls to `$wbenchLoop` but only three of
them will be specialized because of `-fspec-constr-count` being set to three by
default.

This results in:

* One of the four benchmarks "mysteriously" being slower.
* The performance of benchmarks "mysteriously" changing if they are reordered as
  that affects which functions get specialized.
* Similarly the performance of a benchmarks might change if new benchmarks are
  added or other benchmarks removed.

# Potential workarounds

## Ensure that bench isn't inlined.

Since SpecConstr currently won't generate specializations of functions defined in
other modules. Therefore  if `bench` is prevented from inlining this would prevent SpecConstr
from tiggering on it.

Alternatively `bench` could also be marked as `OPAQUE` for newer versions of GHC for similar effect.

This would add some (constant) overhead to benchmarks but would sidestep the SpecConstr issue
and should prevent users from running into this issue in most common scenarios.

## Recommend users to disable SpecConstr

This will stabilize results as no occurrences of bench will get specialized.
However this results in slightly higher overhead for the benchmarking framework.

## Recommend users to set `-fspec-constr-count` to a large number.

This can solve the issue by ensuring all occurrences will be specialized equally.

**Comment by Bodigrim** [comment]
https://github.com/Bodigrim/tasty-bench/blob/fd30b627a6d6c12f98f071e8372315b81dd4b57e/src/Test/Tasty/Bench.hs#L1245-L1249

@AndreasPK I'm sorry, I don't quite follow, what exactly can SpecConstr specialise here?

Would passing `GHC.Exts.SPEC` help?

**Comment by Bodigrim** [comment]
I checked Core of `bytestring` benchmarks.

```haskell
benchIndices_$s$wbenchLoop2
  :: ByteString -> Word64# -> State# RealWorld -> State# RealWorld
benchIndices_$s$wbenchLoop2
  = \ (x_s3Me :: ByteString)
      (ww_s3Mh :: Word64#)
      (eta_s3Mj :: State# RealWorld) ->
      case ww_s3Mh of wild_X1 {
        __DEFAULT ->
          case seq#
                 (case x_s3Me of { BS ww1_s3NJ ww2_s3NK ww3_s3NL ->
                  case $weta1 ww1_s3NJ ww2_s3NK ww3_s3NL of wild2_i3hw {
                    Nothing -> Nothing;
                    Just x1_i3hx -> case x1_i3hx of { I# ipv_i3hc -> wild2_i3hw }
                  }
                  })
                 eta_s3Mj
          of
          { (# ipv_i3sR, ipv1_i3sS #) ->
          benchIndices_$s$wbenchLoop2
            x_s3Me (subWord64# wild_X1 1##64) ipv_i3sR
          };
        0##64 -> eta_s3Mj
      }
end
```

AFAIU the effect of specialization is that the function has been specialized to inline `instance NFData (Maybe a)`. I think it's a good effect: indeed we'd rather have less overhead caused by `benchLoop`.

**Comment by Bodigrim** [comment]
@AndreasPK what do you think about 9c8699014b9ab449e442c15a9ef11473a730a831? It seems to resolve the issue for `bytestring`: now everything is as specialized as possible.

**Comment by AndreasPK** [comment]
> @AndreasPK what do you think about [9c86990](https://github.com/Bodigrim/tasty-bench/commit/9c8699014b9ab449e442c15a9ef11473a730a831)? It seems to resolve the issue for `bytestring`: now everything is as specialized as possible.

Using SPEC isn't something I had considered but should work. I that's the only way tasty-bench runs into the SpecConstr issue that's probably good enough.

**Comment by Bodigrim** [comment]
Thanks for the report and for the analysis, @AndreasPK! I'll merge 9c86990 then.
