### ISSUE TITLE
Benchmarks sometimes get stuck

### ISSUE THREAD

**Issue by konsumlamm** [Bodigrim/tasty-bench#46]
I unfortunately don't have a reproducible example, as this doesn't happen deterministically, but sometimes the benchmarks seem to get stuck. Restarting the benchmarks usually fixes the problem.

**Comment by Bodigrim** [comment]
And no suggestions to set `-t100`in stderr? You might try setting `debug` build flag.

**Comment by konsumlamm** [comment]
Eventually, I get

```
This benchmark takes more than 100 seconds. Consider setting --timeout, if this is unexpected (or to silence this warning).
```

Is this to be expected? The benchmarks shouldn't vary too much and when rerunning, it doesn't occur, so this feels like some bug.

**Comment by Bodigrim** [comment]
This is expected, either set `--timeout 100`, or alternatively increase `--stdev`.
