### ISSUE TITLE
How to remove "All" from every entry

### ISSUE THREAD

**Issue by ribosomerocker** [Bodigrim/tasty-bench#49]
The prefix "All" is repeated in every single benchmark entry. Is there a way to disable that?

**Comment by Bodigrim** [comment]
Entry of what?

**Comment by ribosomerocker** [comment]
Benchmark entry, this is the output I'm getting from something rather standard: https://termpad.com/ImpossibleRepulsiveMagician

**Comment by Bodigrim** [comment]
How about `sed 's/All.//g'`?

**Comment by ribosomerocker** [comment]
Yep, that's what I'm doing right now, but it looks like it's sort of redundant in the benches and it would make it a tiny bit easier to parse for me.

**Comment by Bodigrim** [comment]
https://github.com/Bodigrim/tasty-bench/blob/d8d48cedde7c4d6c1566612d21308c95ded4b8a0/src/Test/Tasty/Bench.hs#L1242-L1249

Instead of calling `Tasty.Bench.defaultMain`, you can inline it and replace `"All"` with anything you like, e. g., an empty string.

**Comment by ribosomerocker** [comment]
Oh, alright. Thank you very much. Sorry for using issues sort of like guide questions. Cheers!
