### ISSUE TITLE
Print more digits?

### ISSUE THREAD

**Issue by mitchellwrosen** [Bodigrim/tasty-bench#53]
Hi, is it possible to print more digits in the output?

For example, I see a benchmark allocates approximately `1.9 G`; is it possible to show e.g. `1.867 G` instead?

Thanks!

**Comment by Bodigrim** [comment]
Are you looking to make it configurable or just one more digit would suffice? So `1.87 G` instead of `1.9 G`.

**Comment by mitchellwrosen** [comment]
Oh, I was wondering if it's configurable. I'm happy with the defaults, but I was curious to see more significant digits for a particular benchmark I'm working on.

**Comment by Bodigrim** [comment]
There seems to be no action points, thus closing. Feel free to reopen if there are further questions / suggestions / ideas.
