### ISSUE TITLE
How to avoid excessive GC

### ISSUE THREAD

**Issue by wismill** [Bodigrim/tasty-bench#56]
So I have the following situation in [`unicode-data`](https://github.com/composewell/unicode-data):
- Bench function on chars.
- Lots of codepoints are unassigned or private use area, so we want to filter these out.
- We do not want the filtering be part of the benchmark, so we use `env` to create a list of chars to bench.
- This big list seems to trigger the GC anyway, giving every unstable results.

Lately I have experimented [a hack](https://github.com/wismill/unicode-data/blob/f312c8a4dd6c90b9067705f62f0cf13d3ddf533c/unicode-data-scripts/bench/Main.hs#L44) that creates a pinned “list” using the foreign interface. This is ugly but seems to work, thanks to pinned memory being excluded from GC.

@Bodigrim What do you think? Is there a better way? Note that we would like to keep the dependencies as small as possible.

**Comment by Bodigrim** [comment]
@wismill maybe pack "interesting" `Char`s into a `ByteArray` instead of list?

**Comment by wismill** [comment]
You mean using e.g. [`newPinnedByteArray`](https://hackage.haskell.org/package/primitive-0.9.0.0/docs/Data-Primitive-ByteArray.html#v:newPinnedByteArray)? But then I guess I can just reach for `newPinnedByteArray#` and further functions from `GHC.Exts`.

Anyway, you confirmed that pinned memory a good direction. It may be worth noting it in the `README`.

**Comment by Bodigrim** [comment]
Not necessarily even pinned, copying continuous blocks of memory is extremely fast on modern processors. And any arrays over 3-4K are automatically pinned by RTS.
