### ISSUE TITLE
Inaccurate memory stats

### ISSUE THREAD

**Issue by meooow25** [Bodigrim/tasty-bench#62]
Reported memory stats seem to be inaccurate because it depends on whether GC has occurred in the benchmarked function.

Here is the program I'm trying to benchmark.

```hs
{- cabal:
build-depends: base, pcre2, tasty-bench, text
-}
import qualified Data.Text as T
import qualified Text.Regex.Pcre2 as Pcre2

import Test.Tasty.Bench

main :: IO ()
main = defaultMain
  [ bench "gsub" $ whnf gsub t
  ]
  where
    !t = T.replicate 10000 (T.singleton 'a')

gsub :: T.Text -> T.Text
gsub t = Pcre2.gsub (T.singleton 'a') (T.singleton 'b') t
{-# NOINLINE gsub #-}
```

On my system with `+RTS -T`, the result is almost always

```
  gsub:       OK
    938  μs ±  87 μs,   0 B  allocated,   0 B  copied, 7.0 MB peak memory
```

though `gsub` allocates of course.

If I instead benchmark

```hs
gsubWithGC :: T.Text -> T.Text
gsubWithGC t = unsafePerformIO $ do
  let !t' = Pcre2.gsub (T.singleton 'a') (T.singleton 'b') t
  performMinorGC
  pure t'
{-# NOINLINE gsubWithGC #-}
```

I get correct stats.

```
  gsubWithGC: OK
    914  μs ±  47 μs,  40 KB allocated, 179 B  copied, 6.0 MB peak memory
```

Perhaps `tasty-bench` should trigger a GC before collecting memory stats?

**Comment by Bodigrim** [comment]
Could you make a PR please to make it clearer what you mean?

**Comment by meooow25** [comment]
Maybe I didn't explain myself well enough.

Consider this program.

```hs
{- cabal:
build-depends: base, primitive
-}
import GHC.Stats
import Data.Primitive.ByteArray

main :: IO ()
main = do
  before <- getRTSStats
  a <- newByteArray 100000
  after <- getRTSStats
  putStrLn $ "allocated_bytes=" <> show (allocated_bytes after - allocated_bytes before)
```
The output is
```
allocated_bytes=0
```

This is because the RTS stats are updated when there is a GC, and there will likely not be any between `before` and `after`.

`tasty-bench`'s code is similar.

https://github.com/Bodigrim/tasty-bench/blob/2786e990d37e0823df3d661a7149ee9faeb9cf06/src/Test/Tasty/Bench.hs#L1105-L1108

It is quite likely that running `act n` will perform some GCs, but it's not guaranteed. This is what I ran into with the `pcre2` benchmark above.

If we update the `before`/`after` program to perform a GC, we get

```diff
@@ -3,4 +3,5 @@
 -}
 import GHC.Stats
+import System.Mem
 import Data.Primitive.ByteArray

@@ -9,4 +10,5 @@
   before <- getRTSStats
   a <- newByteArray 100000
+  performMinorGC
   after <- getRTSStats
   putStrLn $ "allocated_bytes=" <> show (allocated_bytes after - allocated_bytes before)
```
```
allocated_bytes=103064
```
(Though I don't know what all of those extra 3064 bytes are)

Similarly we could add a `performMinorGC` before https://github.com/Bodigrim/tasty-bench/blob/2786e990d37e0823df3d661a7149ee9faeb9cf06/src/Test/Tasty/Bench.hs#L1108

Does that seem reasonable? If yes, I can make the PR.

**Comment by Bodigrim** [comment]
Yes, please make a PR.

**Comment by meooow25** [comment]
> (Though I don't know what all of those extra 3064 bytes are)

My program was flawed. It also needs a GC right before `before`. With that, I get

```
allocated_bytes=101112
```

* 16 bytes overhead for the `ByteArray#`
* 1096 bytes for the `before` `RTSStats` object

An `RTSStats` object is this large because, surprisingly, all the fields are boxed. I can file a GHC issue later suggesting they be unboxed.
