### ISSUE TITLE
Duplicate benchmark names result in nonsensical comparisons

### ISSUE THREAD

**Issue by sjakobi** [Bodigrim/tasty-bench#9]
For example in `bytestring`:

```
$ cabal bench --benchmark-options '--csv baseline.csv -p traversals'
<snip>
    map (+1): OK (0.22s)
      217 μs ±  11 μs
    map (+1): OK (0.45s)
       52 ns ± 1.3 ns

All 2 tests passed (0.69s)
Benchmark bytestring-bench: FINISH
$ cabal bench --benchmark-options '--baseline baseline.csv -p traversals'
<snip>
    map (+1): OK (0.23s)
      206 μs ±  11 μs
    map (+1): OK (0.23s)
       53 ns ± 3.3 ns, 99% faster than baseline

All 2 tests passed (0.45s)
Benchmark bytestring-bench: FINISH
```

The 99% improvement is reported because this benchmark is compared to the result of the much slower other benchmark of the same name.

**Comment by sjakobi** [comment]
BTW, I've started to really enjoy using `tasty-bench`! It has great ergonomics and options like `--file-if-{faster,slower}` are exactly what I've always needed even when I didn't realize it! :)

**Comment by sjakobi** [comment]
I think `tasty-bench` could possibly output a warning when it detects duplicate benchmark names. Outright failure might be too inconvenient.

**Comment by Bodigrim** [comment]
@sjakobi thanks for kind words :)

Could you please try 8b378d9?

**Comment by sjakobi** [comment]
> Could you please try [8b378d9](https://github.com/Bodigrim/tasty-bench/commit/8b378d9224ed63c44affa94051678817e3d95475)?

Thanks! The error message is good, but unfortunately a bit mangled…

```
Running 1 benchmarks...
Benchmark bytestring-bench: RUNNING...
Sanity checks:
 lengths of input data: [10000,10000,10000,10000,10000,10000,10000]
CSV report cannot All
  traversals
    map (+1): proceed, because name 'All.traversals.map (+1)' corresponds to two or more benchmarks. Please disambiguate them.
Benchmark bytestring-bench: ERROR
cabal: Benchmarks failed for bench:bytestring-bench from bytestring-0.11.1.0.
```

**Comment by Bodigrim** [comment]
I'm afraid this is a difficult-to-avoid side effect of running two reporters (`csvReporter` and `consoleBenchReporter`) in parallel.

**Comment by sjakobi** [comment]
Yeah. Seems good enough. Many thanks! :)
